package com.fnol.util;

public class StringConstant {

	public static final String SELECT_NAME = "SELECT * FROM hotel where name=?";
	public static final String SELECT_CITY = "SELECT * FROM hotel where city=?";

	public static final String INSERT_INSURED_DETAILS = "INSERT INTO INSURED_PERSON(CASE_NBR,PREFIX,FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,EMAIL_ID,"
			+ "MARRIAGE_STATUS,DOB,PHONE_NUMBER,CITY,STATE,COUNTRY,SSN,STREET_NAME,STREET_NUMBER,ZIP_CODE,"
			+ "CREATE_DATE,CREATED_BY) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,'Himanshu')";

	public static final String UPDATE_LOCK="UPDATE INSURED_PERSON SET DRIVER_DETAILS_LOCK='Y' WHERE CASE_NBR=?";


	public static final String VALIDATE_INSURED_PERSON = "select EMAIL_I "
			+ "	 from insured_person where trunc(dob)=trunc(to_date(?,'DD-mm-YY')) AND PHONE_NUMBER=? AND case_nbr=? AND DRIVER_DETAILS_LOCK is null";

	public static final String INSERT_DRIVER_DETAILS = "INSERT INTO DRIVER_DETAILS(DRIVER_DETAILS_SEQ,CASE_NBR,PREFIX,FIRST_NAME,"
			+ " MIDDLE_NAME ,LAST_NAME ,EMAIL_ID,DOB,GENDER,MARRIAGE_STATUS,RELATION,LICENSE_STATUS,DRIVER_STATUS,DRIVINING_EXPERIENCE,"
			+ " LICENSE_NUMBER,TRAFFIC_VOLIATION,TRAFFIC_ACCIDENT,VECHILE_VIN_NUMBER,VECHILE_COMPANY,VECHILE_MODEL,VECHILE_NUMBER,"
			+ " VECHILE_MODEL_YEAR,CREATE_DATE,CREATE_BY)"
			+ " VALUES(DRIVER_DETAILS_SEQ.nextval,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?)";

	public static final String INSERT_DRIVER_DOCUMENT = "INSERT INTO DRIVERS_DOCUMENT(DOCUMENT_SEQ ,CASE_NBR ,FIRST_DOC_FILE_NAME,FIRST_DOC_FILE_TYPE,"
			+ "FIRST_DOC_FILE_SIZE,FIRST_DOC_FILE_DESCRIPTION,SECOND_DOC_FILE_NAME,"
			+ " SECOND_DOC_FILE_TYPE,SECOND_DOC_FILE_SIZE,SECOND_DOC_FILE_DESCRIPTION,"
			+ " THIRD_DOC_FILE_NAME,THIRD_DOC_FILE_TYPE,THIRD_DOC_FILE_SIZE,THIRD_DOC_FILE_DESCRIPTION, FIRST_DOC_FILE_CONTENT,SECOND_DOC_FILE_CONTENT,THIRD_DOC_FILE_CONTENT)"
			+ "VALUES(DRIVERS_DOCUMENT_SEQ.nextval,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

}
